# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Django
        uses: actions/setup-python@v3
        with: 
            python-version: 3.12.2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd friend_me_backend
          pip install -r requirements.txt
          cd ../
      - name: Run python manageserver
        run: |
          cd friend_me_backend
          python manage.py runserver
      - name: Flutter setup
        run: |
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install \
            clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev
          
